-- 'TRADING_VOLUME' 테이블 생성
CREATE TABLE TRADING_VOLUME (
    KOREAN_NAME VARCHAR2(100), -- KOREAN_NAME 열
    TOTAL_TRADE_PRICE NUMBER   -- CANDLE_ACC_TRADE_PRICE 합계
);

DROP TABLE K_REAL_TIME_4;
COMMIT;
-- 'TRADING_VOLUME' 테이블 생성
CREATE TABLE TRADING_VOLUME (
    KOREAN_NAME VARCHAR2(100), -- 종목명
    TOTAL_TRADE_PRICE NUMBER   -- CANDLE_ACC_TRADE_PRICE의 합계
);

INSERT INTO TRADING_VOLUME (KOREAN_NAME, TOTAL_TRADE_PRICE)
SELECT
    KOREAN_NAME,
    SUM(CANDLE_ACC_TRADE_PRICE) AS TOTAL_TRADE_PRICE
FROM (
    SELECT
        KOREAN_NAME,
        CANDLE_ACC_TRADE_PRICE,
        ROW_NUMBER() OVER (
            PARTITION BY KOREAN_NAME
            ORDER BY CANDLE_DATE_TIME_UTC DESC
        ) AS RN
    FROM K_REAL_TIME
)

DROP TABLE K_REAL_TIME_3;
COMMIT;

SELECT *
FROM K_REAL_TIME_3;

WHERE RN <= 20 
GROUP BY KOREAN_NAME;

select KOREAN_NAME, candle_date_time_kst, opinion, confidence
from K_REAL_TIME_3
where korean_name = '비트코인'
order by candle_date_time_kst desc;